export const gridItems = [
    {
        id: 1,
        title: "Global Impact",
        description: "asdfasdfasdf",
        className: "w-[66vw] lg:col-span-3 md:col-span-6 md:row-span-4 lg:min-h-[60vh]",
        imgClassName: "w-full h-full",
        image: "",
    },
    {
        id: 2,
        title: "img1",
        description: "",
        className: "lg:col-span-2 md:col-span-3 md:row-span-2",
        imgClassName: "",
        image: "",
    },
    {
        id: 3,
        title: "img2",
        description: "",
        className: "lg:col-span-2 md:col-span-3 md:row-span-2",
        imgClassName: "",
        image: "",
    },
    {
        id: 4,
        title: "Novelty",
        description: "asdfasdfasdf",
        className: "lg:col-span-2 md:col-span-3 md:row-span-1",
        imgClassName: "",
        image: "",
    },
    {
        id: 5,
        title: "TAMU Impact",
        description: "asdfasdfasdf",
        // className: "md:col-span-3 md:row-span-2",
        className: "w-20 h-20 border-8",
        imgClassName: "absolute right-0 bottom-0 md:w-96 w-60",
        image: "",
    },
    {
        id: 6,
        title: "img3",
        description: "",
        //className: "md:col-span-3 md:row-span-2",
        className: "lg:col-span-1 lg:row-span-1",
        imgClassName: "absolute right-0 bottom-0 md:w-96 w-60",
        image: "",
    },
];